// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6eJaDaDBEi10ey6FMLEI9INYdQ-desA',
    appId: '1:66084333578:web:a66b6fff37950e714c57f3',
    messagingSenderId: '66084333578',
    projectId: 'whatsapp-97169',
    authDomain: 'whatsapp-97169.firebaseapp.com',
    storageBucket: 'whatsapp-97169.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-Vlx1s71GijtjALcQyW1g-Tl1tcGcBM',
    appId: '1:66084333578:android:c1003d68d7f72b4e4c57f3',
    messagingSenderId: '66084333578',
    projectId: 'whatsapp-97169',
    storageBucket: 'whatsapp-97169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAagXGsuskaVcB46DRSVJfpTOnBYOP9P4w',
    appId: '1:66084333578:ios:8e455c3e99fb76a24c57f3',
    messagingSenderId: '66084333578',
    projectId: 'whatsapp-97169',
    storageBucket: 'whatsapp-97169.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAagXGsuskaVcB46DRSVJfpTOnBYOP9P4w',
    appId: '1:66084333578:ios:8e455c3e99fb76a24c57f3',
    messagingSenderId: '66084333578',
    projectId: 'whatsapp-97169',
    storageBucket: 'whatsapp-97169.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6eJaDaDBEi10ey6FMLEI9INYdQ-desA',
    appId: '1:66084333578:web:9a6a915741911dd84c57f3',
    messagingSenderId: '66084333578',
    projectId: 'whatsapp-97169',
    authDomain: 'whatsapp-97169.firebaseapp.com',
    storageBucket: 'whatsapp-97169.appspot.com',
  );

}